### ISSUE TITLE
Error: Cannot find module 'node-pogo-protos'

### ISSUE THREAD

**Issue by Padrino02** [Snorflake/CandyMaker#1]
```
C:\Users\...\Desktop\CandyMaker-master>node index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-pogo-protos'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\FIFA\Desktop\CandyMaker-master\index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

Help

**Comment by ar1a** [comment]
you need to run npm install first, closing because the answer is obvious

**Comment by ar1a** [comment]
Just as a precaution, I've committed 4daa64aa3b8426d2e2a306f935ed5e605d2d39b3
